/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lowca API — Unimplemented Endpoints
 * OpenAPI specification for Lowca features not yet implemented on the mobile client.

**Response Envelope:** All endpoints return a standard envelope:
```json
{ "status": 200, "message": "Success", "data": <T>, "errorCode": null }
```
The `data` field contains the schema documented per endpoint.

**Authentication:** All endpoints (except public ones) require `Authorization: Bearer <accessToken>` header.
 * OpenAPI spec version: 1.0.0
 */
import type {
  AddCartItemRequest,
  CastVoteRequest,
  CheckoutSession,
  CreateGroupSessionRequest,
  CreateNominationRequest,
  GroupParticipant,
  GroupSession,
  InitiateCheckoutRequest,
  JoinGroupSessionRequest,
  Nomination,
  OrderSummary,
  RejectOrderRequest,
  SharedCart,
  UpdateCartItemRequest,
  VoteTally
} from '../types/generated';

import { orvalMutator } from '../../../lib/api/orvalMutator';
export const getLowcaAPIUnimplementedEndpoints = () => {
/**
 * Host creates a group session. Returns the session with a unique inviteToken for sharing.
 * @summary Create a new group ordering session
 */
const createGroupSession = (
    createGroupSessionRequest: CreateGroupSessionRequest,
 ) => {
      return orvalMutator<GroupSession>(
      {url: `/api/GroupSession`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createGroupSessionRequest
    },
      );
    }
  
/**
 * Poll every 5 seconds to detect status changes (lobby → voting → ordering → checkout → fulfilled).
 * @summary Get group session details
 */
const getGroupSession = (
    sessionId: string,
 ) => {
      return orvalMutator<GroupSession>(
      {url: `/api/GroupSession/${sessionId}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Expire / close a group session (Host only)
 */
const expireGroupSession = (
    sessionId: string,
 ) => {
      return orvalMutator<void>(
      {url: `/api/GroupSession/${sessionId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary Join an existing group session via invite token
 */
const joinGroupSession = (
    sessionId: string,
    joinGroupSessionRequest: JoinGroupSessionRequest,
 ) => {
      return orvalMutator<GroupSession>(
      {url: `/api/GroupSession/${sessionId}/join`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: joinGroupSessionRequest
    },
      );
    }
  
/**
 * @summary List active participants (poll every 5 s)
 */
const getGroupSessionParticipants = (
    sessionId: string,
 ) => {
      return orvalMutator<GroupParticipant[]>(
      {url: `/api/GroupSession/${sessionId}/participants`, method: 'GET'
    },
      );
    }
  
/**
 * @summary List branch nominations (poll every 5 s)
 */
const getGroupSessionNominations = (
    sessionId: string,
 ) => {
      return orvalMutator<Nomination[]>(
      {url: `/api/GroupSession/${sessionId}/nominations`, method: 'GET'
    },
      );
    }
  
/**
 * Only allowed when session status is `lobby`.
 * @summary Nominate a branch to the session shortlist
 */
const createNomination = (
    sessionId: string,
    createNominationRequest: CreateNominationRequest,
 ) => {
      return orvalMutator<Nomination>(
      {url: `/api/GroupSession/${sessionId}/nominations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createNominationRequest
    },
      );
    }
  
/**
 * @summary Remove a nomination (Host only, lobby phase only)
 */
const deleteNomination = (
    sessionId: string,
    nominationId: string,
 ) => {
      return orvalMutator<void>(
      {url: `/api/GroupSession/${sessionId}/nominations/${nominationId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * Requires at least one nomination. Transitions session status from `lobby` to `voting`.
 * @summary Start the voting phase (Host only)
 */
const startVoting = (
    sessionId: string,
 ) => {
      return orvalMutator<GroupSession>(
      {url: `/api/GroupSession/${sessionId}/voting/start`, method: 'POST'
    },
      );
    }
  
/**
 * @summary Get live vote tallies (poll every 5 s)
 */
const getVoteTallies = (
    sessionId: string,
 ) => {
      return orvalMutator<VoteTally[]>(
      {url: `/api/GroupSession/${sessionId}/votes`, method: 'GET'
    },
      );
    }
  
/**
 * Each member may cast exactly one vote. Session must be in `voting` status.
 * @summary Cast one vote on a nominated branch
 */
const castVote = (
    sessionId: string,
    castVoteRequest: CastVoteRequest,
 ) => {
      return orvalMutator<void>(
      {url: `/api/GroupSession/${sessionId}/votes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: castVoteRequest
    },
      );
    }
  
/**
 * Winner is the branch with most votes; first-nominated branch wins ties. Transitions status to `ordering`. Locks `winnerBranchId` immutably.
 * @summary Close voting and declare winner (Host only)
 */
const closeVoting = (
    sessionId: string,
 ) => {
      return orvalMutator<GroupSession>(
      {url: `/api/GroupSession/${sessionId}/voting/close`, method: 'POST'
    },
      );
    }
  
/**
 * @summary Get the shared cart (poll every 3 s during ordering phase)
 */
const getSharedCart = (
    sessionId: string,
 ) => {
      return orvalMutator<SharedCart>(
      {url: `/api/GroupSession/${sessionId}/cart`, method: 'GET'
    },
      );
    }
  
/**
 * Item is attributed to the calling user. Session must be in `ordering` status and cart must not be locked.
 * @summary Add a dish to the shared cart
 */
const addCartItem = (
    sessionId: string,
    addCartItemRequest: AddCartItemRequest,
 ) => {
      return orvalMutator<SharedCart>(
      {url: `/api/GroupSession/${sessionId}/cart/items`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addCartItemRequest
    },
      );
    }
  
/**
 * Members may only update their own items. Cart must not be locked.
 * @summary Update quantity of own cart item
 */
const updateCartItem = (
    sessionId: string,
    itemId: string,
    updateCartItemRequest: UpdateCartItemRequest,
 ) => {
      return orvalMutator<SharedCart>(
      {url: `/api/GroupSession/${sessionId}/cart/items/${itemId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateCartItemRequest
    },
      );
    }
  
/**
 * @summary Remove own cart item
 */
const removeCartItem = (
    sessionId: string,
    itemId: string,
 ) => {
      return orvalMutator<SharedCart>(
      {url: `/api/GroupSession/${sessionId}/cart/items/${itemId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * Locks the cart for 5 minutes. Host selects payment method. Funds collected upfront via VietQR/bank transfer and held in escrow.
 * @summary Lock cart and initiate checkout (Host only)
 */
const initiateCheckout = (
    sessionId: string,
    initiateCheckoutRequest: InitiateCheckoutRequest,
 ) => {
      return orvalMutator<CheckoutSession>(
      {url: `/api/GroupSession/${sessionId}/checkout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: initiateCheckoutRequest
    },
      );
    }
  
/**
 * @summary Get checkout / escrow status (poll every 5 s)
 */
const getCheckoutStatus = (
    sessionId: string,
 ) => {
      return orvalMutator<CheckoutSession>(
      {url: `/api/GroupSession/${sessionId}/checkout`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Cancel checkout and unlock cart (Host only, before payment completes)
 */
const cancelCheckout = (
    sessionId: string,
 ) => {
      return orvalMutator<void>(
      {url: `/api/GroupSession/${sessionId}/checkout`, method: 'DELETE'
    },
      );
    }
  
/**
 * Releases escrow funds to the vendor. Transitions session to `fulfilled`.
 * @summary Vendor accepts the group order
 */
const acceptGroupOrder = (
    sessionId: string,
 ) => {
      return orvalMutator<GroupSession>(
      {url: `/api/GroupSession/${sessionId}/order/accept`, method: 'POST'
    },
      );
    }
  
/**
 * Triggers immediate full refund to Host's wallet. Transitions session to `rejected`.
 * @summary Vendor rejects the group order
 */
const rejectGroupOrder = (
    sessionId: string,
    rejectOrderRequest?: RejectOrderRequest,
 ) => {
      return orvalMutator<GroupSession>(
      {url: `/api/GroupSession/${sessionId}/order/reject`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: rejectOrderRequest
    },
      );
    }
  
/**
 * Available only after session is `fulfilled`. Shows per-member item breakdown.
 * @summary Get read-only post-fulfillment order summary
 */
const getOrderSummary = (
    sessionId: string,
 ) => {
      return orvalMutator<OrderSummary>(
      {url: `/api/GroupSession/${sessionId}/summary`, method: 'GET'
    },
      );
    }
  
return {createGroupSession,getGroupSession,expireGroupSession,joinGroupSession,getGroupSessionParticipants,getGroupSessionNominations,createNomination,deleteNomination,startVoting,getVoteTallies,castVote,closeVoting,getSharedCart,addCartItem,updateCartItem,removeCartItem,initiateCheckout,getCheckoutStatus,cancelCheckout,acceptGroupOrder,rejectGroupOrder,getOrderSummary}};
export type CreateGroupSessionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['createGroupSession']>>>
export type GetGroupSessionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['getGroupSession']>>>
export type ExpireGroupSessionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['expireGroupSession']>>>
export type JoinGroupSessionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['joinGroupSession']>>>
export type GetGroupSessionParticipantsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['getGroupSessionParticipants']>>>
export type GetGroupSessionNominationsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['getGroupSessionNominations']>>>
export type CreateNominationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['createNomination']>>>
export type DeleteNominationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['deleteNomination']>>>
export type StartVotingResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['startVoting']>>>
export type GetVoteTalliesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['getVoteTallies']>>>
export type CastVoteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['castVote']>>>
export type CloseVotingResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['closeVoting']>>>
export type GetSharedCartResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['getSharedCart']>>>
export type AddCartItemResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['addCartItem']>>>
export type UpdateCartItemResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['updateCartItem']>>>
export type RemoveCartItemResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['removeCartItem']>>>
export type InitiateCheckoutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['initiateCheckout']>>>
export type GetCheckoutStatusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['getCheckoutStatus']>>>
export type CancelCheckoutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['cancelCheckout']>>>
export type AcceptGroupOrderResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['acceptGroupOrder']>>>
export type RejectGroupOrderResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['rejectGroupOrder']>>>
export type GetOrderSummaryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['getOrderSummary']>>>
