/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lowca API — Unimplemented Endpoints
 * OpenAPI specification for Lowca features not yet implemented on the mobile client.

**Response Envelope:** All endpoints return a standard envelope:
```json
{ "status": 200, "message": "Success", "data": <T>, "errorCode": null }
```
The `data` field contains the schema documented per endpoint.

**Authentication:** All endpoints (except public ones) require `Authorization: Bearer <accessToken>` header.
 * OpenAPI spec version: 1.0.0
 */
import type {
  BranchCampaignInfo,
  CreateRestaurantCampaignRequest,
  GetNearbyCampaignsParams,
  GetPublicCampaignsParams,
  NearbyCampaign,
  QuestResponse,
  RestaurantCampaign,
  SystemCampaign,
  UserQuestProgress,
  VendorCampaignBranch,
} from '../types/generated';

import { orvalMutator } from '../../../../lib/api/orvalMutator';
export const getLowcaAPIUnimplementedEndpoints = () => {
  /**
   * Only available to Silver tier or higher vendors. Diamond vendors are auto-enrolled.
   * @summary List active system (platform-wide) campaigns
   */
  const getSystemCampaigns = (params?: {
    page?: number;
    pageSize?: number;
  }) => {
    return orvalMutator<{
      currentPage: number;
      pageSize: number;
      totalPages: number;
      totalCount: number;
      hasPrevious: boolean;
      hasNext: boolean;
      items: SystemCampaign[];
    }>({
      url: `/api/Campaign/system`,
      method: 'GET',
      params,
    });
  };

  /**
   * @summary Opt in to a system campaign
   */
  const joinSystemCampaign = (campaignId: string) => {
    return orvalMutator<SystemCampaign>({
      url: `/api/Campaign/system/${campaignId}/join`,
      method: 'POST',
    });
  };

  /**
   * Returns active voucher campaigns from verified vendors near the user (or all if no location provided).
   * @summary List available restaurant (vendor) voucher campaigns
   */
  const getPublicCampaigns = (params?: GetPublicCampaignsParams) => {
    return orvalMutator<{
      currentPage: number;
      pageSize: number;
      totalPages: number;
      totalCount: number;
      hasPrevious: boolean;
      hasNext: boolean;
      items: RestaurantCampaign[];
    }>({
      url: `/api/Campaign/public`,
      method: 'GET',
      params,
    });
  };

  /**
   * Requires active subscription and verified vendor status.
   * @summary Vendor creates a direct-claim voucher campaign
   */
  const createRestaurantCampaign = (
    createRestaurantCampaignRequest: CreateRestaurantCampaignRequest
  ) => {
    return orvalMutator<RestaurantCampaign>({
      url: `/api/Campaign/restaurant`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createRestaurantCampaignRequest,
    });
  };

  /**
   * Returns paid push campaigns from vendors within range of the user's current location.
   * @summary Get GPS-triggered nearby push campaigns
   */
  const getNearbyCampaigns = (params: GetNearbyCampaignsParams) => {
    return orvalMutator<NearbyCampaign[]>({
      url: `/api/Campaign/nearby`,
      method: 'GET',
      params,
    });
  };

  /**
   * @summary List active quests, optionally filtered by campaign
   */
  const getPublicQuests = (params?: {
    campaignId?: number;
    pageNumber?: number;
    pageSize?: number;
  }) => {
    return orvalMutator<{
      currentPage: number;
      pageSize: number;
      totalPages: number;
      totalCount: number;
      hasPrevious: boolean;
      hasNext: boolean;
      items: QuestResponse[];
    }>({
      url: `/api/Quest/public`,
      method: 'GET',
      params,
    });
  };

  /**
   * @summary Get the current user's quest progress for a specific campaign
   */
  const getCampaignQuestProgress = (campaignId: string) => {
    return orvalMutator<UserQuestProgress[]>({
      url: `/api/Quest/campaign/${campaignId}/my-progress`,
      method: 'GET',
    });
  };

  /**
   * @summary Enroll the current user in a quest
   */
  const enrollInQuest = (questId: number) => {
    return orvalMutator<UserQuestProgress>({
      url: `/api/Quest/${questId}/enroll`,
      method: 'POST',
    });
  };

  /**
   * Returns all branches participating in any vendor-created campaign, sorted by score.
   * Anonymous endpoint — no auth required.
   * @summary List branches in any active vendor campaign
   */
  const getVendorCampaignBranches = (params?: {
    pageNumber?: number;
    pageSize?: number;
    lat?: number | null;
    lng?: number | null;
    distance?: number | null;
  }) => {
    return orvalMutator<{
      currentPage: number;
      pageSize: number;
      totalPages: number;
      totalCount: number;
      hasPrevious: boolean;
      hasNext: boolean;
      items: VendorCampaignBranch[];
    }>({
      url: `/api/Campaign/vendor/branches`,
      method: 'GET',
      params,
    });
  };

  /**
   * Anonymous endpoint — no auth required.
   * @summary List active vendor campaigns for a specific branch
   */
  const getVendorCampaignsByBranch = (
    branchId: number,
    params?: { isWorking?: boolean }
  ) => {
    return orvalMutator<BranchCampaignInfo[]>({
      url: `/api/Campaign/vendor/branch/${branchId}`,
      method: 'GET',
      params,
    });
  };

  return {
    getSystemCampaigns,
    joinSystemCampaign,
    getPublicCampaigns,
    createRestaurantCampaign,
    getNearbyCampaigns,
    getPublicQuests,
    getCampaignQuestProgress,
    enrollInQuest,
    getVendorCampaignBranches,
    getVendorCampaignsByBranch,
  };
};
export type GetSystemCampaignsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['getSystemCampaigns']
    >
  >
>;
export type JoinSystemCampaignResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['joinSystemCampaign']
    >
  >
>;
export type GetPublicCampaignsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['getPublicCampaigns']
    >
  >
>;
export type CreateRestaurantCampaignResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getLowcaAPIUnimplementedEndpoints
      >['createRestaurantCampaign']
    >
  >
>;
export type GetNearbyCampaignsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['getNearbyCampaigns']
    >
  >
>;
