export const VALIDATE_ERROR_MESSAGES = {
  REQUIRED: 'validation.required',
  EMPTY_PHONE_NUMBER: 'validation.empty_phone_number',
  EMPTY_EMAIL: 'validation.empty_email',
  INVALID_EMAIL: 'validation.invalid_email',
  EMPTY_USERNAME: 'validation.empty_username',
  MIN_USERNAME_LENGTH: 'validation.min_username_length',
  MAX_USERNAME_LENGTH: 'validation.max_username_length',
  EMPTY_PASSWORD: 'validation.empty_password',
  EMPTY_CONFIRM_PASSWORD: 'validation.empty_confirm_password',
  PASSWORD_MIN_LENGTH: 'validation.password_min_length',
  EMPTY_OTP: 'validation.empty_otp',
  INVALID_OTP: 'validation.invalid_otp',
  EMPTY_NEW_PASSWORD: 'validation.empty_new_password',
  NEW_PASSWORD_MIN_LENGTH: 'validation.new_password_min_length',
  INVALID_PHONE_NUMBER: 'validation.invalid_phone_number',
  PASSWORD_MISMATCH: 'validation.password_mismatch',
  EMPTY_NAME: 'validation.empty_name',
  EMPTY_LAST_NAME: 'validation.empty_last_name',
  INVALID_NAME: 'validation.invalid_name',
  INVALID_LAST_NAME: 'validation.invalid_last_name',
  EMPTY_FIRST_NAME: 'validation.empty_first_name',
  USERNAME_MIN_LENGTH: 'validation.username_min_length',
} as const;
