/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lowca API — Unimplemented Endpoints
 * OpenAPI specification for Lowca features not yet implemented on the mobile client.

**Response Envelope:** All endpoints return a standard envelope:
```json
{ "status": 200, "message": "Success", "data": <T>, "errorCode": null }
```
The `data` field contains the schema documented per endpoint.

**Authentication:** All endpoints (except public ones) require `Authorization: Bearer <accessToken>` header.
 * OpenAPI spec version: 1.0.0
 */
import type {
  BranchTier,
  FeedbackSubmitResponse,
  SubmitFeedbackRequest,
  VelocityCheckResponse,
} from '../types/generated';

import { orvalMutator } from '../../../../lib/api/orvalMutator';
export const getLowcaAPIUnimplementedEndpoints = () => {
  /**
   * Tier is derived from the sliding window of the last 20 reviews. Possible tiers: `diamond`, `gold`, `silver`, `warning`.
   * @summary Get the current tier of a branch
   */
  const getBranchTier = (branchId: string) => {
    return orvalMutator<BranchTier>({
      url: `/api/Branch/${branchId}/tier`,
      method: 'GET',
    });
  };

  /**
   * Requires user to be within 50 metres of the stall (GPS geo-fence). Velocity limits: max 1 review per stall per day, max 3 total per day.
   * @summary Submit a review for a branch
   */
  const submitFeedback = (
    branchId: string,
    submitFeedbackRequest: SubmitFeedbackRequest
  ) => {
    return orvalMutator<FeedbackSubmitResponse>({
      url: `/api/Feedback/branch/${branchId}`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: submitFeedbackRequest,
    });
  };

  /**
   * @summary Check remaining review quota for the current day
   */
  const checkReviewVelocity = () => {
    return orvalMutator<VelocityCheckResponse>({
      url: `/api/Feedback/velocity/check`,
      method: 'GET',
    });
  };

  return { getBranchTier, submitFeedback, checkReviewVelocity };
};
export type GetBranchTierResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['getBranchTier']
    >
  >
>;
export type SubmitFeedbackResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['submitFeedback']
    >
  >
>;
export type CheckReviewVelocityResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getLowcaAPIUnimplementedEndpoints
      >['checkReviewVelocity']
    >
  >
>;
