/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lowca API — Unimplemented Endpoints
 * OpenAPI specification for Lowca features not yet implemented on the mobile client.

**Response Envelope:** All endpoints return a standard envelope:
```json
{ "status": 200, "message": "Success", "data": <T>, "errorCode": null }
```
The `data` field contains the schema documented per endpoint.

**Authentication:** All endpoints (except public ones) require `Authorization: Bearer <accessToken>` header.
 * OpenAPI spec version: 1.0.0
 */
import type {
  AddPersonalCartItemRequest,
  GetMyOrdersParams,
  Order,
  PaginatedOrders,
  PersonalCart,
  PlaceOrderRequest,
  UpdatePersonalCartItemRequest,
} from '../types/generated';

import { orvalMutator } from '../../../lib/api/orvalMutator';
export const getLowcaAPIUnimplementedEndpoints = () => {
  /**
   * Each user has at most one active personal cart per branch. Returns an empty cart (items: []) if nothing has been added yet.
   * @summary Get the current user's personal cart for a specific branch
   */
  const getPersonalCart = (branchId: string) => {
    return orvalMutator<PersonalCart>({
      url: `/api/Cart/${branchId}`,
      method: 'GET',
    });
  };

  /**
   * @summary Clear all items from the personal cart for a branch
   */
  const clearPersonalCart = (branchId: string) => {
    return orvalMutator<void>({
      url: `/api/Cart/${branchId}`,
      method: 'DELETE',
    });
  };

  /**
   * If the dish already exists in the cart, its quantity is incremented rather than creating a duplicate entry.
   * @summary Add a dish to the personal cart
   */
  const addPersonalCartItem = (
    branchId: string,
    addPersonalCartItemRequest: AddPersonalCartItemRequest
  ) => {
    return orvalMutator<PersonalCart>({
      url: `/api/Cart/${branchId}/items`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: addPersonalCartItemRequest,
    });
  };

  /**
   * @summary Update quantity of a personal cart item
   */
  const updatePersonalCartItem = (
    branchId: string,
    itemId: string,
    updatePersonalCartItemRequest: UpdatePersonalCartItemRequest
  ) => {
    return orvalMutator<PersonalCart>({
      url: `/api/Cart/${branchId}/items/${itemId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updatePersonalCartItemRequest,
    });
  };

  /**
   * @summary Remove a specific item from the personal cart
   */
  const removePersonalCartItem = (branchId: string, itemId: string) => {
    return orvalMutator<PersonalCart>({
      url: `/api/Cart/${branchId}/items/${itemId}`,
      method: 'DELETE',
    });
  };

  /**
   * Converts the personal cart for the given branch into a confirmed order. The cart is cleared on success. Payment is collected upfront via the selected method.
   * @summary Place an order from the personal cart
   */
  const placeOrder = (placeOrderRequest: PlaceOrderRequest) => {
    return orvalMutator<Order>({
      url: `/api/Order`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: placeOrderRequest,
    });
  };

  /**
   * @summary Get the current user's order history
   */
  const getMyOrders = (params?: GetMyOrdersParams) => {
    return orvalMutator<PaginatedOrders>({
      url: `/api/Order`,
      method: 'GET',
      params,
    });
  };

  /**
   * Poll this endpoint every 10 seconds on the OrderStatusScreen to track live order status changes.
   * @summary Get a single order by ID
   */
  const getOrder = (orderId: string) => {
    return orvalMutator<Order>({ url: `/api/Order/${orderId}`, method: 'GET' });
  };

  /**
   * Only allowed when order status is `pending`. Triggers immediate refund to customer wallet.
   * @summary Customer cancels a pending order
   */
  const cancelOrder = (orderId: string) => {
    return orvalMutator<Order>({
      url: `/api/Order/${orderId}/cancel`,
      method: 'POST',
    });
  };

  return {
    getPersonalCart,
    clearPersonalCart,
    addPersonalCartItem,
    updatePersonalCartItem,
    removePersonalCartItem,
    placeOrder,
    getMyOrders,
    getOrder,
    cancelOrder,
  };
};
export type GetPersonalCartResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['getPersonalCart']
    >
  >
>;
export type ClearPersonalCartResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['clearPersonalCart']
    >
  >
>;
export type AddPersonalCartItemResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getLowcaAPIUnimplementedEndpoints
      >['addPersonalCartItem']
    >
  >
>;
export type UpdatePersonalCartItemResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getLowcaAPIUnimplementedEndpoints
      >['updatePersonalCartItem']
    >
  >
>;
export type RemovePersonalCartItemResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getLowcaAPIUnimplementedEndpoints
      >['removePersonalCartItem']
    >
  >
>;
export type PlaceOrderResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['placeOrder']
    >
  >
>;
export type GetMyOrdersResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['getMyOrders']
    >
  >
>;
export type GetOrderResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['getOrder']>
  >
>;
export type CancelOrderResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getLowcaAPIUnimplementedEndpoints>['cancelOrder']
    >
  >
>;
