/**
 * Hardcoded list of common HCM street food dish names used for search suggestions.
 * Covers the most popular dishes across noodles, rice, bread, snacks, and drinks.
 */
export const DISH_KEYWORDS: string[] = [
  // Noodle soups
  'Phở bò',
  'Phở gà',
  'Phở tái',
  'Phở nạm',
  'Bún bò Huế',
  'Bún riêu',
  'Bún mắm',
  'Bún mộc',
  'Bún cá',
  'Bún thái',
  'Bún mọc',
  'Bún sườn',
  'Hủ tiếu',
  'Hủ tiếu Nam Vang',
  'Hủ tiếu gõ',
  'Hủ tiếu sa tế',
  'Mì Quảng',
  'Mì vịt tiềm',
  'Mì hoành thánh',
  'Mì sủi cảo',
  'Bánh canh',
  'Bánh canh cua',
  'Bánh canh ghẹ',
  'Bánh canh giò heo',
  'Cháo',
  'Cháo lòng',
  'Cháo sườn',
  'Cháo trắng',

  // Rice dishes
  'Cơm tấm',
  'Cơm gà',
  'Cơm chiên',
  'Cơm sườn',
  'Cơm niêu',
  'Cơm cháy',
  'Cơm rang dưa bò',
  'Cơm gà xối mỡ',
  'Xôi',
  'Xôi mặn',
  'Xôi gà',
  'Xôi bắp',
  'Xôi lá dứa',

  // Bread & wraps
  'Bánh mì',
  'Bánh mì thịt',
  'Bánh mì chả cá',
  'Bánh mì xíu mại',
  'Gỏi cuốn',
  'Bì cuốn',
  'Chả giò',
  'Bò bía',
  'Bánh tráng trộn',
  'Bánh tráng nướng',
  'Bánh tráng cuốn',
  'Bánh cuốn',
  'Bánh xèo',
  'Bánh bèo',
  'Bánh bột lọc',
  'Bánh ướt',
  'Bánh ướt lòng gà',
  'Bánh hỏi',
  'Bột chiên',
  'Bột lọc chiên',
  'Há cảo',
  'Sủi cảo',

  // Grilled & BBQ
  'Bún thịt nướng',
  'Bún chả',
  'Nem nướng',
  'Thịt xiên nướng',
  'Cá viên chiên',
  'Bò viên chiên',
  'Tôm viên chiên',
  'Chân gà nướng',
  'Cút lộn xào me',
  'Trứng cút nướng',
  'Vịt quay',

  // Hotpot & stir-fry
  'Lẩu',
  'Lẩu bò',
  'Lẩu hải sản',
  'Mì xào',
  'Hủ tiếu xào',
  'Miến xào cua',
  'Phá lấu',
  'Ốc',
  'Ốc len xào dừa',
  'Ốc hương rang muối',
  'Ốc móng tay xào tỏi',
  'Sò điệp nướng mỡ hành',
  'Sò lông nướng',
  'Nghêu hấp sả',

  // Desserts & drinks
  'Chè',
  'Chè khúc bạch',
  'Chè bưởi',
  'Chè thái',
  'Chè đậu đen',
  'Chè đậu đỏ',
  'Chè trôi nước',
  'Sinh tố',
  'Sữa chua dẻo',
  'Sữa chua trân châu',
  'Sữa tươi trân châu đường đen',
  'Nước mía',
  'Nước dừa',
  'Nước sâm',
  'Rau má đậu',
  'Cà phê sữa đá',
  'Bạc xỉu',
  'Cacao đá',
  'Trà đào',
  'Trà chanh',
  'Trà tắc',
  'Trà atiso',
  'Trà sữa',
];

export const useDishKeywords = (): string[] => DISH_KEYWORDS;
